# http://nick-dunn.co.uk/blog/jekyll-github-travis-ci-sitting-in-a-tree/
language: ruby
rvm:
- 2.4
script:
- bundle exec jekyll build
after_success:
- git clone https://$GITHUB_REPO
- cd $(basename ${GITHUB_REPO%.git})
- git config user.name "Travis CI"
- git config user.email ${EMAIL}
- rsync -az --delete --exclude '.git*' ../_site/ .
# - touch .nojekyll
- git add -A .
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/ecole-des-lettres/ecole-des-lettres-magazine.git
  - REPO_TARGET_BRANCH: live
  - secure: jtlCtR9RlIKs/zIbSpIWlZhx71OjMz0qXIyxZoPZG4O0E3/18QyOBkJIno16XIigzk1PxkCQx/vA+nFfkgzragd7tn5jjiD4uzh/Lz2Qfeyr1rzmNP6Y9BViNkvm1VU12kzQileH9NMft8mAuq8loZ6UP2muI8kxAJR3I92JLOvueLoJXo+fgijIoLLxtNbocYh2H3r5+GLt2Wtvbn96sBsVnwR9snAFx/89FgXz1AgoIU0AHsExnRj5uhvJCesITNbHH0sQ5LRL+jYriH2VIFv5bKWKbmB6CIDCucpbT/JpOl86qDNxVYcxwT9N81aNqXpZezcWwfMYOEc/Dbz/mkWOy5fzl1kBWzNs08tUrBn0QVhlVedzGR98Mdtih8PLMjRk0C2udZkEf0hnw98HnJoqw4LE+3Ij49dLb6G0MkFfDtTrOZUZfWHuDc8Aj1YufVrYDkJkpzZoKztXmN7/RJtJ9+4chxMm00gOoEL10PjfDvXGP4z9lGMDX0Yhh8/sEffKQFXPJlg2o2xmahSRdGRgNYwc8jh3mlHp4RJF6t6a7wwpFcUS99359qzhRJbm/r8IeBxJ4TCS+IX4qi4JMqBxEGsRlzy2akvcGH9tS5Xa1CqC1T1jrgORABYJAvwwJAaoHNLNXwlQjxH9HjEq3A2jyR+DvIXa7Ccr38BoMF4=
