url: 'http://www.ecoledeslettres.fr'
baseurl: '/pages'
permalink: :year/:title.html
lang: fr

exclude:
  - vendor
  - gems
  - Gemfile
  - .gitignore
  - assets
  - Rakefile

collections:
  sommaires:
    output: true
  zoomsur:
    output: true
  documentalistes:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: posts
    values:
      layout: "default"
  - scope:
      path: "pages/"
      type: pages
    values:
      permalink: "/:title.html"
  - scope:
      path: "_sommaires/"
    values:
      permalink: sommaires/:year/:title.html
      type: "pages"
  - scope:
      path: "_zoomsur/"
      type: "zoomsur"
    values:
      permalink: zoomsur/:year/:title.html
      type: "pages"
  - scope:
      path: "_documentalistes/"
      type: "documentalistes"
    values:
      permalink: documentalistes/:year/:title.html
      type: "pages"

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-default-layout

titles_from_headings:
  enabled:     true
  strip_title: true
