# backend:
#   name: github
#   repo: ecole-des-lettres/ecole-des-lettres-magazine # Path to your Github repository
#   branch: master # Branch to update (master by default)

backend:
  name: git-gateway

media_folder: "images/" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "sommaires" # Used in routes, ie.: /admin/collections/:slug/edit
    label: Sommaires" # Used in the UI, ie.: "New Post"
    folder: "_sommaires/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Numéro", name: "numero", widget: "number"}
      - {label: "Année", name: "annee", widget: "string"}
      - {label: Image, name: image, widget: image, required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - name: article
        label: Articles
        widget: list
        required: false
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image, required: false}
          - {label: Auteur, name: auteur, widget: string}
          - {label: "Contenu", name: "body", widget: "markdown"}
  - name: "articles" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Articles" # Used in the UI, ie.: "New Post"
    folder: "_articles/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - label: "Niveaux"
        name: "niveau_etudes"
        widget: "list"
        default: ["cours préparatoire", "cours élémentaire", "cours moyen", "sixième", "cinquième", "quatrième", "troisième", "seconde", "seconde technologique", "première", "première technologique", "terminale", "bac pro", "BTS", "classes préparatoires et concours", "agrégation", "CAPES"]
      - label: "Auteurs"
        name: "auteurs"
        widget: "list"
      - label: "Œuvres"
        name: "oeuvres"
        widget: "list"
      - label: "Réalisateurs"
        name: "realisateurs"
        widget: "list"
  - name: "zoomsur" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Zoom Sur" # Used in the UI, ie.: "New Post"
    folder: "_zoomsur/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
  - name: "documentalistes" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Documentalistes" # Used in the UI, ie.: "New Post"
    folder: "_documentalistes/"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Année", name: "annee", widget: "string"}
      - {label: "Pages", name: "pages", widget: "number"}
      - {label: "Rubrique", name: "rubrique", widget: "string"}
      - {label: "Revue", name: "revue", widget: "string"}
      #- {label: "PDF", name: "article_pdf", widget: "string"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
